# Generated by Django 5.1.6 on 2025-02-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
